### ISSUE TITLE
Symbol clashes with standalone `zix` library

### ISSUE THREAD

**Issue by fogti** [drobilla/sord#5]
original issue occured in: https://github.com/NixOS/nixpkgs/pull/190218

Zrythm (https://git.sr.ht/~alextee/zrythm) links against liblilv, which links against libsord, which includes a copy of libzix. But zrythm also links directly against libzix, which leads to symbol clashes, and subsequently causes segfaults.

A solution would be a release of sord with an explicit dependency on zix (this would be relatively clean), or a conditional dependency on zix (e.g. meson/configure flag).
Also, the interface of the standalone zix library appears to be different from the version of zix included here, explaining the segfault above...

**Comment by fogti** [comment]
on that note: Can we please introduce some sort of symbol/API versioning into zix to prevent this in the future, given that the zix API still changes rapidly, and also to future-proof it?

**Comment by drobilla** [comment]
I do intend to release zix as a "proper" library shortly, but these symbols shouldn't be publicly exposed in sord.  At the moment the zix bits in sord are just private implementation details.

If it was intended to be suiltable for packaging and sharing between projects, it would be released and properly versioned, but it's not, so it isn't.

**Comment by fogti** [comment]
the interesting thing is pretty much that this was just exposed by dynamic (maybe weak idk) linking, and appears to "just work" when statically linking it, which was the reason it wasn't noticed at/before the zrythm beta release.

The problem is basically just that private symbols from `sord` with prefix `zix_` leak into the public symbol table, which causes symbol clashes downstream. Solution e.g. https://stackoverflow.com/a/437525 (probably needs some testing...)

I guess the problem lies here:
https://github.com/drobilla/sord/blob/70b16298f30c8ca91032abbadead945f6ce8fa07/src/zix/common.h#L19-L20

maybe replace that with:
```c
#elif defined(__GNUC__) && !defined(ZIX_STATIC)
#  define ZIX_API __attribute__((visibility("default")))
#elif defined(__GNUC__)
#  define ZIX_API __attribute__((visibility("hidden")))
```

**Comment by drobilla** [comment]
Ah, yeah, the macro setup got botched.  Fixed in 4611148, thanks.

**Comment by zseri** [comment]
They still appear to be exposed:
```

[nix-shell:~/devel/sord/build]$ cat ~/tmp/sord-nm-old 
                 U calloc@GLIBC_2.2.5
000000000000c008 b completed.0
                 w __cxa_finalize@GLIBC_2.2.5
00000000000034a0 t deregister_tm_clones
0000000000003510 t __do_global_dtors_aux
000000000000bb48 d __do_global_dtors_aux_fini_array_entry
000000000000c000 d __dso_handle
000000000000bb50 d _DYNAMIC
0000000000003860 t error
000000000000892c t _fini
                 U __fprintf_chk@GLIBC_2.3.4
0000000000003550 t frame_dummy
000000000000bb40 d __frame_dummy_init_array_entry
000000000000a6f0 r __FRAME_END__
                 U free@GLIBC_2.2.5
0000000000006fc0 t free_node_entry
000000000000bd70 d _GLOBAL_OFFSET_TABLE_
                 w __gmon_start__
00000000000092a8 r __GNU_EH_FRAME_HDR
0000000000003000 t _init
                 w _ITM_deregisterTMCloneTable
                 w _ITM_registerTMCloneTable
                 U malloc@GLIBC_2.2.5
                 U memcmp@GLIBC_2.2.5
                 U memcpy@GLIBC_2.14
                 U memmove@GLIBC_2.2.5
0000000000009140 r orderings
00000000000034d0 t register_tm_clones
                 U serd_env_expand
                 U serd_env_get_base_uri
                 U serd_env_set_base_uri
                 U serd_env_set_prefix
                 U serd_node_equals
                 U serd_node_free
                 U serd_node_from_string
                 U serd_node_new_uri_from_node
                 U serd_node_new_uri_from_string
0000000000009280 r SERD_NODE_NULL
                 U serd_reader_new
                 U serd_reader_set_default_graph
                 U serd_strlen
                 U serd_uri_string_has_scheme
                 U serd_writer_end_anon
                 U serd_writer_write_statement
0000000000009200 r sizes
0000000000007ce0 T sord_add
0000000000006c80 T sord_ask
0000000000005d80 T sord_begin
0000000000006c60 T sord_contains
0000000000006c10 T sord_count
00000000000080c0 T sord_erase
0000000000006100 T sord_find
0000000000005e30 T sord_free
0000000000007000 T sord_get
0000000000005d50 T sord_get_world
0000000000008380 T sord_inserter_free
0000000000008780 T sord_inserter_new
0000000000008390 T sord_inserter_set_base_uri
00000000000083a0 T sord_inserter_set_prefix
00000000000083b0 T sord_inserter_write_statement
0000000000007090 t sord_insert_node
0000000000005880 T sord_iter_end
00000000000058c0 T sord_iter_free
0000000000005760 T sord_iter_get
0000000000005750 T sord_iter_get_model
0000000000005890 T sord_iter_get_node
00000000000057b0 T sord_iter_next
00000000000043a0 t sord_iter_scan_next.part.0
00000000000058f0 T sord_new
00000000000071a0 T sord_new_blank
00000000000072f0 T sord_new_literal
00000000000087b0 T sord_new_reader
0000000000007b50 T sord_new_relative_uri
00000000000079c0 T sord_new_uri
0000000000007480 t sord_new_uri_counted
0000000000006ff0 T sord_node_copy
0000000000005690 T sord_node_equals
0000000000006f30 T sord_node_free
0000000000007610 T sord_node_from_serd_node
0000000000007610 t sord_node_from_serd_node.localalias
0000000000006ee0 T sord_node_get_datatype
0000000000006ef0 T sord_node_get_flags
0000000000006ec0 T sord_node_get_language
0000000000006d00 T sord_node_get_string
0000000000006e90 T sord_node_get_string_counted
0000000000006ea0 T sord_node_get_string_measured
0000000000006ce0 T sord_node_get_type
0000000000005040 t sord_node_hash
00000000000037e0 t sord_node_hash_equal
0000000000006f00 T sord_node_is_inline_object
0000000000006f20 T sord_node_to_serd_node
0000000000005d70 T sord_num_nodes
0000000000005d60 T sord_num_quads
0000000000006d10 t sord_quad_compare
00000000000056a0 T sord_quad_match
0000000000007e40 T sord_remove
0000000000006bb0 T sord_search
0000000000005650 T sord_world_free
0000000000005600 T sord_world_new
0000000000005680 T sord_world_set_error_sink
00000000000088d0 T sord_write
0000000000008820 T sord_write_iter
                 U __stack_chk_fail@GLIBC_2.4
                 U stderr@GLIBC_2.2.5
                 U strcmp@GLIBC_2.2.5
                 U strlen@GLIBC_2.2.5
                 U strncmp@GLIBC_2.2.5
                 U strncpy@GLIBC_2.2.5
000000000000c008 d __TMC_END__
                 U __vfprintf_chk@GLIBC_2.3.4
0000000000008520 t write_statement
0000000000004100 T zix_btree_begin
00000000000041a0 T zix_btree_end
0000000000004e90 T zix_btree_find
0000000000003b70 T zix_btree_free
0000000000003560 t zix_btree_free_rec
00000000000040e0 T zix_btree_get
0000000000003bb0 T zix_btree_insert
00000000000041d0 T zix_btree_iter_copy
0000000000004250 T zix_btree_iter_equals
0000000000004870 T zix_btree_iter_free
00000000000042b0 T zix_btree_iter_increment
0000000000004230 T zix_btree_iter_is_end
0000000000003f00 T zix_btree_lower_bound
0000000000003990 t zix_btree_merge
0000000000003ae0 T zix_btree_new
0000000000004880 T zix_btree_remove
0000000000003640 t zix_btree_rotate_left
0000000000003720 t zix_btree_rotate_right
0000000000003ba0 T zix_btree_size
0000000000005010 T zix_digest_add
0000000000005090 T zix_digest_add_64
00000000000050a0 T zix_digest_add_ptr
0000000000005000 T zix_digest_start
00000000000051d0 T zix_hash_find
00000000000055a0 T zix_hash_foreach
0000000000005150 T zix_hash_free
0000000000005240 T zix_hash_insert
00000000000050c0 T zix_hash_new
0000000000005440 T zix_hash_remove
00000000000051c0 T zix_hash_size
```
The last commit didn't change that. (`t` = afaik properly hidden, `T` = public)

**Comment by fogti** [comment]
ok, works now.
